"""LIT wrappers for MiniDalleModel."""

from collections.abc import Iterable

from lit_nlp.api import model as lit_model
from lit_nlp.api import types as lit_types
from lit_nlp.lib import image_utils
from min_dalle import MinDalle
import numpy as np
from PIL import Image
import torch


class DalleMiniModel(lit_model.Model):
  """LIT model wrapper for Dalle-Mini Text-to-Image model.

  This wrapper simplifies the pipeline using Dalle-Mini for text-to-image
  generation.


  The basic flow within this model wrapper's predict() function is:


  1. Dalle-Mini processes the text prompt.
  2. Images are directly generated by Dalle-Mini.
  """

  def __init__(
      self,
      device: str = "cuda",  # Use "cuda" for GPU or "cpu" for CPU
      grid_size: int = 4,  # each batch will generate grid_size**2 images
      temperature: float = 0.5,
      top_k: int = 256,
      supercondition_factor: int = 32,
  ):
    super().__init__()
    self.grid_size = grid_size
    self.temperature = temperature
    self.top_k = top_k
    self.supercondition_factor = supercondition_factor

    # Load Dalle-Mini model
    self.model = MinDalle(
        models_root="./pretrained",
        dtype=torch.float32,
        device=device,
        is_mega=True,
        is_reusable=True,
    )

  def max_minibatch_size(self) -> int:
    return 8

  def predict(
      self, inputs: Iterable[lit_types.JsonDict], **unused_kw
  ) -> Iterable[lit_types.JsonDict]:
    """Generate images based on the input prompts."""

    def tensor_to_pil_image(tensor):
      img_np = tensor.detach().cpu().numpy()
      img_np = np.squeeze(img_np)
      if img_np.ndim == 2:
        img_np = np.stack([img_np] * 3, axis=-1)
      elif img_np.ndim != 3 or img_np.shape[2] != 3:
        raise ValueError(
            f"Unexpected image shape: {img_np.shape}. Expected (H, W, 3)."
        )

      img_np = (img_np - img_np.min()) / (img_np.max() - img_np.min()) * 255
      img_np = img_np.clip(0, 255).astype(np.uint8)
      return Image.fromarray(img_np)

    prompts = [ex["prompt"] for ex in inputs]
    images = []
    for prompt in prompts:
      # Generate images using the model
      generated_images = self.model.generate_images(
          text=prompt,
          seed=-1,
          grid_size=self.grid_size,
          is_seamless=False,
          temperature=self.temperature,
          top_k=self.top_k,
          supercondition_factor=self.supercondition_factor,
          is_verbose=False,
      )
      pil_images = []
      for img_tensor in generated_images:
        pil_images.append(tensor_to_pil_image(img_tensor))
      images.append({
          "image": [
              image_utils.convert_pil_to_image_str(img) for img in pil_images
          ],
          "prompt": prompt,
      })

    return images

  def input_spec(self):
    return {"prompt": lit_types.TextSegment()}

  def output_spec(self):
    return {
        "image": lit_types.ImageBytesList(),
        "prompt": lit_types.TextSegment(),
    }
